name: Check new patch
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
jobs:
  check:
    name: Check new patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check GitHub connection
        id: check-gh
        run: bash src/etc/connection.sh

      - name: Check new patch Instagram Beta
        id: check-instagram-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh meta/instagram-beta prerelease instagram-beta.apk

      - name: Check new patch ReVanced YouTube Beta
        id: check-revanced-youtube-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh ReVanced/revanced-patches prerelease youtube-beta.apk

      - name: Check new patch ReVanced YouTube Music Beta
        id: check-revanced-youtube-music-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh ReVanced/revanced-patches prerelease yt-music-beta.apk

      - name: Keep workflow run
        if: steps.check-gh.outputs.internet_error == '0'
        uses: gautamkrishnar/keepalive-workflow@v1

    outputs:
      check_instagram_beta: ${{ steps.check-instagram-beta.outputs.new_patch }}
      check_revanced_youtube_beta: ${{ steps.check-revanced-youtube-beta.outputs.new_patch }}
      check_revanced_yt_music_beta: ${{ steps.check-revanced-youtube-music-beta.outputs.new_patch }}

  Patch-Instagram-Beta:
    name: Patch Instagram Beta
    needs: check
    if: ${{ needs.check.outputs.check_instagram_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Instagram Beta"

  Patch-Revanced-YouTube-Beta:
    name: Patch ReVanced YouTube Beta
    needs: check
    if: ${{ needs.check.outputs.check_revanced_youtube_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "ReVanced YouTube Beta"

  Patch-Revanced-YouTube-Music-Beta:
    name: Patch ReVanced YouTube Music Beta
    needs: check
    if: ${{ needs.check.outputs.check_revanced_yt_music_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "ReVanced YouTube Music Beta"
